steps:
  # Build the container image.
  - name: 'gcr.io/oden-qa/balena-build:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        docker build -t buildtest:latest .

  # run the container image.
  - name: 'gcr.io/oden-qa/balena-build:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        docker run --privileged buildtest:latest

