steps:
  # run the container image.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    secretEnv:
      - BALENA_TOKEN
    args:
      - '-xc'
      - |
        docker run --privileged -e BALENA_TOKEN -v /workspace:/workspace docker:stable-dind /workspace/outer_test.sh

secrets:
  - kmsKeyName: projects/useful-flame-255619/locations/global/keyRings/my-keyring/cryptoKeys/enc-key
    secretEnv:
      BALENA_TOKEN: CiQAKomhUuncJ3BU948o+lhY+2eAnIlTFIkAQEnmfmFTestOmrYSSQCVdaAvrQws+RpMA62ammFLAaawzFYo5gNai1vjXxVFqxDwSk/M11ryWUYbyqiH233o4aetm3rT600WT6wreInUz4CyR9j2qLQ=
