steps:
  # run the container image.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args:
      - '-xc'
      - |
              dd if=/dev/zero of=/workspace/disk-image count=1 bs=1M && docker build -f Dockerfile.outer -t outer && docker run --privileged --rm -v /workspace/disk-image:/disk-image outer
