FROM docker:stable-dind
WORKDIR /usr/src/app
COPY Dockerfile.inner .
ENV DOCKER_HOST unix:///var/run/docker.sock
CMD dockerd & sleep 5 && docker build -f Dockerfile.inner -t inner . && docker run --privileged -v /disk-image:/disk-image inner
